language: cpp
sudo: required
dist: trusty 
compiler:
- g++
os:
- linux
before_script: 
- sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
- sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++
- g++ --version
- wget http://releases.llvm.org/4.0.0/clang+llvm-4.0.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz
- tar xf clang+llvm-4.0.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz 
- export PATH=${PWD}/clang+llvm-4.0.0-x86_64-linux-gnu-ubuntu-14.04:$PATH
- cmake -DLLVM_DIR=clang+llvm-4.0.0-x86_64-linux-gnu-ubuntu-14.04/lib/cmake .
script:
- make VERBOSE=1
- sudo make install
branches:
  only:
  - master
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - cmake 
notifications:
  email: false
